service: art-party-deploy-trigger
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  checkAndTriggerDeploy:
    handler: index.run
    memorySize: 128
    ssmToEnvironment:
      - GITHUB_TOKEN
      - INSTA_COOKIE
      - INSTA_LOGIN
      - INSTA_PASSWORD
    events:
      # Invoke Lambda function every hour
      - schedule: rate(1 hour)

custom:
  serverlessSsmFetch:
    GITHUB_TOKEN: /artparty/GITHUB_TOKEN
    INSTA_COOKIE: /artparty/INSTA_COOKIE
    INSTA_LOGIN: /artparty/INSTA_LOGIN~true
    INSTA_PASSWORD: /artparty/INSTA_PASSWORD~true

plugins:
  - serverless-ssm-fetch